### ISSUE TITLE
有兴趣上crates.io吗

### ISSUE THREAD

**Issue by Snake1999** [yingDev/rxrs#2]
我所在的项目组很喜欢你的响应式编程库，希望在自己的项目里使用。我们有一个打算用rust重写的大型游戏服务器项目，需要使用一个响应式编程架构。如果你的项目能推到crates会方便不少。谢谢

以上
林木兰
[Nukkit项目组](http://github.com/nukkit)

**Comment by yingDev** [comment]
这个项目距离实际应用还有相当一段距离。到时候才会发布。也许还需要一个月。

**Comment by Snake1999** [comment]
好吧，谢谢回复
等你的好消息：）

**Comment by BatmanAoD** [comment]
@yingDev Should this ticket be closed now that the project is on crates.io?
